[I 13:24:01.349 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.8
[I 13:24:01.351 NotebookApp] Serving notebooks from local directory: /home/ubuntu/speech-recognition-challenge
[I 13:24:01.351 NotebookApp] 0 active kernels
[I 13:24:01.351 NotebookApp] The Jupyter Notebook is running at:
[I 13:24:01.351 NotebookApp] https://[all ip addresses on your system]:8888/
[I 13:24:01.351 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 13:24:10.941 NotebookApp] 404 GET /notebooks/speech-recognition-challenge/Test.ipynb (24.193.30.2): No such file or directory: speech-recognition-challenge/Test.ipynb
[W 13:24:10.969 NotebookApp] 404 GET /notebooks/speech-recognition-challenge/Test.ipynb (24.193.30.2) 28.29ms referer=https://k80.soph.info:8888/notebooks/speech-recognition-challenge/Untitled.ipynb?kernel_name=python3
[I 13:24:17.992 NotebookApp] 302 GET / (24.193.30.2) 0.50ms
[C 13:24:37.440 NotebookApp] received signal 15, stopping
[I 13:24:37.440 NotebookApp] Shutting down 0 kernels
